version: '2'
services:
    jvm-build:
        build: .
        image: jvm-build:compose
        container_name: "jvm-build"
        network_mode: "host"
        volumes:
        - .:/pwd
        - /var/run/docker.sock:/var/run/docker.sock
        - /opt/docker:/opt/docker
        stdin_open: true
        tty: true
        command: /bin/bash
